apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyterhub-deployment
  labels:
    app: jupyterhub
spec:
  selector:
    matchLabels:
      app: jupyterhub
  replicas: 1
  template:
    metadata:
      labels:
        app: jupyterhub
    spec:
      containers:
        - name: jupyterhub
          image: jupyterhub/jupyterhub:1.4.2
          ports:
            - containerPort: 8000
          env:
            - name: JUPYTERHUB_CRYPT_KEY
              value: "APQT"
            - name: JUPYTERHUB_AUTHENTICATOR_CLASS
              value: "dummyauthenticator.DummyAuthenticator"
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "500Mi"
