apiVersion: v1
kind: Service
metadata:
  name: jupyterhub
  labels:
    app: jupyterhub
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: jupyterhub
