apiVersion: v1
kind: Service
metadata:
  name: jupyterhub-service
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8000
  selector:
    app: jupyterhub
